version: '3.7'

services:
  service:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
    - ./services/web/:/usr/src/app/
    ports:
    - 5000:5000
    env_file:
    - services/env/.env.dev
    depends_on:
    - db
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
    - database/env/.env.dev
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - API_URL=localhost:5000/api
    environment:
      - NODE_ENV=development
    volumes:
    - ./client:/app
    - ./client/node_modules:/app/node_modules
    ports:
    - '3001:3000'
    depends_on:
    - service

volumes:
  postgres_data:
