# build environment
FROM node:13 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . /app
RUN npm install --silent
RUN npm install react-scripts@3.3.0 -g --silent
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
ARG API_URL
ENV REACT_APP_API_URL $API_URL
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]